version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
    - mkdir -p target/stg
    - mkdir target/prod
    - serverless deploy -v -r ap-south-1

artifacts:
  files:
  - target/**/*
  - serverless.yml
  - deploy.sh